// main.js

// Função para carregar dados do armazenamento local
function loadData(profession) {
    return JSON.parse(localStorage.getItem(profession)) || [];
    }

    // Função para salvar dados no armazenamento local
    function saveData(profession, data) {
        localStorage.setItem(profession, JSON.stringify(data));
        }

        // Função para adicionar dados de casos (Advogado)
        document.getElementById('case-form')?.addEventListener('submit', function(event) {
            event.preventDefault();
                const clientName = document.getElementById('client-name').value;
                    const caseDetails = document.getElementById('case-details').value;
                        const cases = loadData('advogados');
                            cases.push({ clientName, caseDetails });
                                saveData('advogados', cases);
                                    alert('Caso cadastrado com sucesso!');
                                        this.reset();
                                        });

                                        // Função para exibir casos (Advogado)
                                        function displayCases() {
                                            const cases = loadData('advogados');
                                                const tableBody = document.getElementById('case-table-body');
                                                    cases.forEach(c => {
                                                            const row = tableBody.insertRow();
                                                                    row.insertCell(0).textContent = c.clientName;
                                                                            row.insertCell(1).textContent = c.caseDetails;
                                                                                });
                                                                                }
                                                                                if (document.getElementById('case-table-body')) {
                                                                                    displayCases();
                                                                                    }

                                                                                    // Função para adicionar dados de projetos (Arquiteto)
                                                                                    document.getElementById('project-form')?.addEventListener('submit', function(event) {
                                                                                        event.preventDefault();
                                                                                            const projectName = document.getElementById('project-name').value;
                                                                                                const projectDetails = document.getElementById('project-details').value;
                                                                                                    const projects = loadData('arquitetos');
                                                                                                        projects.push({ projectName, projectDetails });
                                                                                                            saveData('arquitetos', projects);
                                                                                                                alert('Projeto cadastrado com sucesso!');
                                                                                                                    this.reset();
                                                                                                                    });

                                                                                                                    // Função para exibir projetos (Arquiteto)
                                                                                                                    function displayProjects() {
                                                                                                                        const projects = loadData('arquitetos');
                                                                                                                            const tableBody = document.getElementById('project-table-body');
                                                                                                                                projects.forEach(p => {
                                                                                                                                        const row = tableBody.insertRow();
                                                                                                                                                row.insertCell(0).textContent = p.projectName;
                                                                                                                                                        row.insertCell(1).textContent = p.projectDetails;
                                                                                                                                                            });
                                                                                                                                                            }
                                                                                                                                                            if (document.getElementById('project-table-body')) {
                                                                                                                                                                displayProjects();
                                                                                                                                                                }

                                                                                                                                                                // Função para adicionar dados de planos de aula (Professor)
                                                                                                                                                                document.getElementById('lesson-plan-form')?.addEventListener('submit', function(event) {
                                                                                                                                                                    event.preventDefault();
                                                                                                                                                                        const lessonTitle = document.getElementById('lesson-title').value;
                                                                                                                                                                            const lessonDetails = document.getElementById('lesson-details').value;
                                                                                                                                                                                const lessonPlans = loadData('professores');
                                                                                                                                                                                    lessonPlans.push({ lessonTitle, lessonDetails });
                                                                                                                                                                                        saveData('professores', lessonPlans);
                                                                                                                                                                                            alert('Plano de aula cadastrado com sucesso!');
                                                                                                                                                                                                this.reset();
                                                                                                                                                                                                });

                                                                                                                                                                                                // Função para exibir planos de aula (Professor)
                                                                                                                                                                                                function displayLessonPlans() {
                                                                                                                                                                                                    const lessonPlans = loadData('professores');
                                                                                                                                                                                                        const tableBody = document.getElementById('lesson-plan-table-body');
                                                                                                                                                                                                            lessonPlans.forEach(lp => {
                                                                                                                                                                                                                    const row = tableBody.insertRow();
                                                                                                                                                                                                                            row.insertCell(0).textContent = lp.lessonTitle;
                                                                                                                                                                                                                                    row.insertCell(1).textContent = lp.lessonDetails;
                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        if (document.getElementById('lesson-plan-table-body')) {
                                                                                                                                                                                                                                            displayLessonPlans();
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                            // Função para adicionar dados de pacientes (Médico)
                                                                                                                                                                                                                                            document.getElementById('patient-form')?.addEventListener('submit', function(event) {
                                                                                                                                                                                                                                                event.preventDefault();
                                                                                                                                                                                                                                                    const patientName = document.getElementById('patient-name').value;
                                                                                                                                                                                                                                                        const symptoms = document.getElementById('symptoms').value;
                                                                                                                                                                                                                                                            const patients = loadData('medicos');
                                                                                                                                                                                                                                                                patients.push({ patientName, symptoms });
                                                                                                                                                                                                                                                                    saveData('medicos', patients);
                                                                                                                                                                                                                                                                        alert('Paciente cadastrado com sucesso!');
                                                                                                                                                                                                                                                                            this.reset();
                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                            // Função para exibir pacientes (Médico)
                                                                                                                                                                                                                                                                            function displayPatients() {
                                                                                                                                                                                                                                                                                const patients = loadData('medicos');
                                                                                                                                                                                                                                                                                    const tableBody = document.getElementById('patient-table-body');
                                                                                                                                                                                                                                                                                        patients.forEach(p => {
                                                                                                                                                                                                                                                                                                const row = tableBody.insertRow();
                                                                                                                                                                                                                                                                                                        row.insertCell(0).textContent = p.patientName;
                                                                                                                                                                                                                                                                                                                row.insertCell(1).textContent = p.symptoms;
                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                    if (document.getElementById('patient-table-body')) {
                                                                                                                                                                                                                                                                                                                        displayPatients();
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                        // Função para adicionar dados de requisitos (Engenheiro de Software)
                                                                                                                                                                                                                                                                                                                        document.getElementById('requirement-form')?.addEventListener('submit', function(event) {
                                                                                                                                                                                                                                                                                                                            event.preventDefault();
                                                                                                                                                                                                                                                                                                                                const requirementName = document.getElementById('requirement-name').value;
                                                                                                                                                                                                                                                                                                                                    const requirementDetails = document.getElementById('requirement-details').value;
                                                                                                                                                                                                                                                                                                                                        const requirements = loadData('engenheiros');
                                                                                                                                                                                                                                                                                                                                            requirements.push({ requirementName, requirementDetails });
                                                                                                                                                                                                                                                                                                                                                saveData('engenheiros', requirements);
                                                                                                                                                                                                                                                                                                                                                    alert('Requisito cadastrado com sucesso!');
                                                                                                                                                                                                                                                                                                                                                        this.reset();
                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                        // Função para exibir requisitos (Engenheiro de Software)
                                                                                                                                                                                                                                                                                                                                                        function displayRequirements() {
                                                                                                                                                                                                                                                                                                                                                            const requirements = loadData('engenheiros');
                                                                                                                                                                                                                                                                                                                                                                const tableBody = document.getElementById('requirement-table-body');
                                                                                                                                                                                                                                                                                                                                                                    requirements.forEach(r => {
                                                                                                                                                                                                                                                                                                                                                                            const row = tableBody.insertRow();
                                                                                                                                                                                                                                                                                                                                                                                    row.insertCell(0).textContent = r.requirementName;
                                                                                                                                                                                                                                                                                                                                                                                            row.insertCell(1).textContent = r.requirementDetails;
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                if (document.getElementById('requirement-table-body')) {
                                                                                                                                                                                                                                                                                                                                                                                                    displayRequirements();
                                                                                                                                                                                                                                                                                                                                                                                                    }